apiVersion: v1
kind: Pod
metadata:
  name: circle-server-pod
spec:
  containers:
  - name: circle-server-pod
    image: virendrapatidar/circle-node:latest
    ports:
    - containerPort: 80
    env:
    - name: API_KEY
      value: "TEST_API_KEY:7c187e809486e9c501db53cd5e8aaf60:53f217c580d4ba73d64a2abb7ac69184"
    - name: PORT
      value: "8080"
    - name: DATABASE_FILENAME
      value: "/data/sqlite.db"      
    volumeMounts:
    - name: server-data-volume
      mountPath: /data
  volumes:
  - name: server-data-volume
    hostPath:
      path: "/tmp"
      type: DirectoryOrCreate